export const projects = [
  {
    title: 'Selenium Python Testing Framework',
    description: "This is a code repository for a testing framework that I designed and built from scratch using Selenium, Python and Pytest. The framework is for testing an E-Commerce website. The site tested in this framework is a dummy site I made with wordpress/woocommerce/mamp/mysql loaded with sample data from woocommerce.",
    image: 'https://blog.logrocket.com/wp-content/uploads/2021/11/web-automation-selenium-python.png',
    tags: ['Python', 'Selenium', 'Pytest', 'MySQL'],
    source: 'https://github.com/trevharri/EcommSeleniumPythonFramework',
    visit: 'https://github.com/trevharri/EcommSeleniumPythonFramework',
    id: 4,
  },
  {
    title: 'Spotiflyy',
    description: "A work in progress. A Spotify clone built using React, Redux and Tailwind CSS. In working on this project I am learning more about interacting with APIs in react and complex state management using Redux.",
      image: 'https://i.imgur.com/40IHLNY.png',
      tags: ['React', 'Redux', 'JavaScript', 'Tailwind CSS', 'HTML', 'CSS'],
    source: 'https://github.com/trevharri/Spotiflyy',
    visit: 'https://spotiflyy.vercel.app/',
    id: 3,
  },
  {
    title: 'CryptoStop',
    description: "I built out a responsive Crypto themed landing page using react. In creating this site I practiced and learned concepts such as responsive design (flexbox/gird and media queries), conditional rendering and BEM naming convention. The images and art were generated on Midjourney.",
      image: 'https://i.imgur.com/Jq2Ldqw.png',
      tags: ['React', 'JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/trevharri/project1',
    visit: 'https://gpt3-zeta-green.vercel.app/',
    id: 0,
  },
  {
    title: 'Noogle',
    description: "Using React, Tailwind CSS and a goole search API I created a simple and responsive goole search clone. This project helped me learn how to interact with APIs in react, the useEffect hook and how to create context in react to avoid prop drilling.",
      image: 'https://i.imgur.com/3bUTENe.png',
      tags: ['React', 'JavaScript', 'Tailwind CSS', 'HTML', 'CSS'],
    source: 'https://github.com/trevharri/noogle',
    visit: 'https://noogle-liard.vercel.app',
    id: 1,
  },
  {
    title: 'Movie Fight',
    description:"A single page application with two drop-downs that fetches info about movies from an imdb API and then compares the two and color codes the victor/loser. This project was built in vanilla JavaScript with Bulma CSS. In this project I reinforced my ability to fetch and parse data from APIs, handle errors, debounce function calls and manipulate the DOM in JavaScript.",
    image: 'https://i.imgur.com/mD6fv7L.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/trevharri/movie-fight',
    visit: 'https://movie-fight-smoky.vercel.app/',
    id: 2,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Graduated from University of Minnesota with a Bachelors degree in biology and began working as a Regulatory Data Specialist for Pace Analytical at 3M', },
  { year: 2020, text: 'Became a Regulatory QA Analyst for Pace Analytical at 3M conducting manual testing and using tools such as SQL and Excel', },
  { year: 2021, text: 'Moved to Spain and began my development journy learning Python', },
  { year: 2022, text: 'Started exploring front-end web development learning JavaScript/HTML/CSS/React', },
  { year: 2023, text: 'Earned a Meta Front-End Developer Certificate and began learning test automation', },
];
