export const projects = [
  {
    title: 'CryptoStop',
    description: "I built out a beautiful and responsive Crypto themed landing page using react. In creating this site I practiced and learned concepts such as responsive design (flexbox/gird and media queries), conditional rendering and BEM naming convention. The images and art were generated on Midjourney.",
      image: 'https://i.imgur.com/Jq2Ldqw.png',
      tags: ['React', 'JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/trevharri/project1',
    visit: 'https://gpt3-zeta-green.vercel.app/',
    id: 0,
  },
  {
    title: 'Noogle',
    description: "Using React, Tailwind CSS and a goole search API I created a simple and responsive goole search clone. This project helped me learn how to interact with APIs in react, the useEffect hook and how to create context in react to avoid prop drilling.",
      image: 'https://i.imgur.com/3bUTENe.png',
      tags: ['React', 'JavaScript', 'Tailwind CSS', 'HTML', 'CSS'],
    source: 'https://github.com/trevharri/noogle',
    visit: 'https://noogle-liard.vercel.app',
    id: 1,
  },
  {
    title: 'Movie Fight',
    description:"A single page application with two drop-downs that fetches info about movies from an imdb API and then compares the two and color codes the victor/loser. This project was built in vanilla JavaScript with Bulma CSS. In this project I reinforced my ability to fetch and parse data from APIs, handle errors, debounce function calls and manipulate the DOM in JavaScript.",
    image: 'https://i.imgur.com/mD6fv7L.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/trevharri/movie-fight',
    visit: 'https://movie-fight-smoky.vercel.app/',
    id: 2,
  },
  // {
  //   title: 'WebRTC App',
  //   description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
  //     image: '/images/3.jpg',
  //     tags: ['React', 'WebRTC'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 4,
  // },
];

export const TimeLineData = [
  { year: 2019, text: 'Graduated from University of Minnesota with a Bachelors degree in biology', },
  { year: 2020, text: 'Began working as a Regulatory Data Specialist for Pace Analytical at 3M', },
  { year: 2021, text: 'Became a Regulatory IT Analyst for Pace Analytical at 3M using tools such as SQL Server', },
  { year: 2022, text: 'Started my frontend journy learning JavaScript/React/HTML/CSS', },
  { year: 2023, text: 'Earned a Meta Front-End Developer Certificate and began working on my own projects', },
];
